;;; フォントセットを作る
(let* ((fontset-name "myfonts")
       (size 14)
       (asciifont "Menlo")
       (jpfont "Hiragino Kaku Gothic ProN")
       (font (format "%s-%d:weight=normal:slant=normal" asciifont size))
       (fontspec (font-spec :family asciifont))
       (jp-fontspec (font-spec :family jpfont)) 
       (fsn (create-fontset-from-ascii-font font nil fontset-name)))
  (set-fontset-font fsn 'japanese-jisx0213.2004-1 jp-fontspec)
  (set-fontset-font fsn 'japanese-jisx0213-2 jp-fontspec)
  (set-fontset-font fsn 'katakana-jisx0201 jp-fontspec)
  (set-fontset-font fsn '(#x0080 . #x024F) fontspec)
  (set-fontset-font fsn '(#x0370 . #x03FF) fontspec)
  )
 (add-to-list 'default-frame-alist '(font . "fontset-myfonts"))
 (dolist (elt '(("^-apple-hiragino.*" . 1.1)
	       (".*osaka-bold.*" . 1.1)
	       (".*osaka-medium.*" . 1.1)
	       (".*courier-bold-.*-mac-roman" . 1.0)
	       (".*monaco cy-bold-.*-mac-cyrillic" . 0.9)
	       (".*monaco-bold-.*-mac-roman" . 0.9)))
  (add-to-list 'face-font-rescale-alist elt))
 (set-face-font 'default "fontset-myfonts")
